class Withdraw extends PeatioModel.Model
  @configure 'Withdraw', 'sn', 'account_id', 'member_id', 'currency', 'amount', 'fee', 'fund_uid', 'fund_extra',
    'created_at', 'updated_at', 'done_at', 'txid', 'blockchain_url', 'aasm_state', 'sum', 'type', 'is_submitting'

  constructor: ->
    super
    @is_submitting = @aasm_state == "submitting"

  @initData: (records) ->
    PeatioModel.Ajax.disable ->
      $.each records, (idx, record) ->
        Withdraw.create(record)

  afterScope: ->
    "#{@pathName()}"

  pathName: ->
    switch @currency
      when 'gio' then 'gravios'
      when 'btc' then 'satoshis'
      when 'doge' then 'doges'
      when 'ltc' then 'ltcs'
      when 'eth' then 'ethers'
      when 'psd' then 'poseidons'
      when 'phc' then 'profithunters'
      when 'xgc' then 'xgoldcoins'
      when 'dev' then 'deviants'
      when 'pbs' then 'phoboscoins'
      when 'din' then 'dineros'
      when 'adv' then 'advances'
      when 'dv7' then 'dv7coins'
      when 'jew' then 'shekels'
      when 'argo' then 'argos'
      when 'esco' then 'escrows'
      when 'neet' then 'neetcoins'
      when 'xylo' then 'xylos'
      when 'steep' then 'steepcoins'
      when 'bitg' then 'bitcoingreens'
      when 'crft' then 'craftrs'
      when 'env' then 'enviromints'
      when 'sng' then 'snowgems'
      when 'nyc' then 'newyorkcoins'
      when 'zoc' then 'zeroonecoins'
      when 'btcz' then 'bitcoinzs'
      when 'ytn' then 'yentens'
      when 'yic' then 'yicoins'
      when 'tlp' then 'tulipcoins'
      when 'pwc' then 'pawcoins'
      when 'shnd' then 'stronghands'
      when 'lmn' then 'lemanums'
      when 'kec' then 'keycos'
      when 'abs' then 'absolutes'
      when 'suppo' then 'suppocoins'
      when 'linda' then 'lindas'
      when 'hight' then 'highcoins'
      when 'bls' then 'blisscoins'
      when 'tokc' then 'tokyos'
      when 'elp' then 'elleriumcoins'
      when 'zex' then 'zexcoins'
      when 'rlc' then 'rulitecoins'
      when 'lucky' then 'luckybits'
      when 'ich' then 'instacashcoins'
      when 'mmb' then 'mambocoins'
      when 'pnx' then 'phantomxcoins'
      when 'mix' then 'mixcoins'
      when 'kreds' then 'kredscoins'
      when 'bkt' then 'bankittcoins'
      when 'snx' then 'snxcoins'
      when 'giro' then 'girocoins'
      when 'onex' then 'onexcoins'
      when 'pushi' then 'pushicoins'
      when 'vrt' then 'virtuscoins'
      when 'zaca' then 'zacacoins'
      when 'xhm' then 'xhimeracoins'
      when 'xar' then 'xarucoins'
      when 'rupx' then 'rupayacoins'
      when 'frm' then 'ferrumcoins'
      when 'men' then 'peoplecoins'
      when 'mun' then 'muncoins'
      when 'onemc' then 'millioncoins'
      when 'alp' then 'alphacoins'
      when 'zel' then 'zelcashcoins'
      when 'amx' then 'amerocoins'
      when 'pew' then 'brofistcoins'
      when 'fsc' then 'friendshipcoins'
      when 'sln' then 'salencoins'
      when 'usx' then 'unifiedsocietycoins'
      when 'bsx' then 'bitspacecoins'
      when 'eot' then 'eotcoins'
      when 'xap' then 'apolloncoins'
      when 'miac' then 'miacoins'
      when 'kc' then 'krakencoins'
      when 'arhm' then 'archimedcoins'
      when 'olmp' then 'olympiccoins'
      when 'onz' then 'onzcoins'
      when 'agn' then 'agenacoins'
      when 'crz' then 'corezcoins'
      when 'enix' then 'enixtcoins'
      when 'snc' then 'stannumcoins'
      when 'quaz' then 'quazcoins'
      when 'scriv' then 'scrivcoins'
      when 'ethf' then 'ethfcoins'
      when 'arepa' then 'arepacoins'
      when 'sub1x' then 'sub1xcoins'
      when 'cheese' then 'cheesecoins'
      when 'jiyo' then 'jiyocoins'
      when 'pyro' then 'pyrocoins'
      when 'roe' then 'rovercoins'
      when 'citr' then 'citruscoins'
      when 'xen' then 'xeoncoins'
      when 'edl' then 'edollarcoins'
      when 'cru' then 'curiumcoins'
      when 'ndc' then 'needlecoins'
      when 'zls' then 'zaliascoins'
      when 'proton' then 'protoncoins'
      when 'krait' then 'kraitcoins'
      when 'aln' then 'alphanodecoins'
      when 'bcp' then 'bcpcoins'
      when 'xmx' then 'xumacoins'
      when 'ida' then 'idapaycoins'
      when 'unify' then 'unifycoins'
      when 'and' then 'andcoins'
      when 'vig' then 'thevigcoins'
      when 'peps' then 'pepegoldcoins'
      when 'vizz' then 'vizzotopcoins'
      #currency

window.Withdraw = Withdraw
